### ISSUE TITLE
Perf tests for stateware and dot-prop-immutable

### ISSUE THREAD

**Issue by zmitry** [wellguimaraes/stateware#1]
https://github.com/zhDmitry/statewarePerfTests
Take a look on this pref tests. It looks that dot prop uses optima algorithm for updating arrays and object. It also gives you nice api for updating nested values without big perf reduction.

I guess stateware api  could be something like this.
```
const iState = createState({ }, { dotprop: true,  computed: true }) // i guess the defaults should be true but would be useful to turn off one of it
iState.set(['path', 'to' 'value'], value or func func from prevValue);
```
set, get, delete, merge, toggle - methods from dotprop with binded value for first argument.

What do you think about this improvement  ?

**Comment by wellguimaraes** [comment]
Hey @zhDmitry, looks good! I've seen another interesting lib do deal with nested immutable data: https://github.com/Zenika/immutadot

Its utilities are mostly based on lodash, so there're some extra features... Maybe too much? Dunno... Anyway, dot prop performance looks really good. We could test them both to make those features available.

**Comment by zmitry** [comment]
@wellguimaraes i also have tested performance with ramda it looks awesome too.
Maybe  we should add more cases for testing.

**Comment by markerikson** [comment]
For what it's worth, there's at least a couple dozen immutable update utility libraries out there.  See the [Immutable Data#Immutable Update Utilities](https://github.com/markerikson/redux-ecosystem-links/blob/master/immutable-data.md#immutable-update-utilities) section of my Redux addons catalog for a list.

Also, quick side question.  I'm not exactly clear on the use case for Stateware.  Is it intended as a replacement for Redux, or a replacement for using plain JS objects _inside_ of Redux?

**Comment by wellguimaraes** [comment]
@markerikson no, it's not a replacement for Redux. The idea is to avoid computing values every time you change related values. With stateware you have getters/selectors functions, which are automatically memoized, this way, they're not computed every time the state updates, but only when dependencies update.

**Comment by wellguimaraes** [comment]
@markerikson The goal is similar to [reselect](https://github.com/reactjs/reselect), but with a different approach. For me, it looks clearer and less verbose.
