### ISSUE TITLE
One of the sources for assign has an enumerable key on the prototype chain error.

### ISSUE THREAD

**Issue by abeltje1** [wellguimaraes/stateware#2]
Hi!

First of all: I really love the simplicity and power of combining stateware and actionware, truly truly awesome work!!!

But... I can't figure out how to get stateware working sadly enough. I'm trying to use both together with redux (in a react native app) but every time I add smart state functions, like filteredUsers, I get the following error: 'One of the sources for assign has an enumerable key on the prototype chain. Are you trying to assign a prototype property? We don't allow it, as this is an edge case we do not support.'

This error only shows up after adding smart state functions, if I use createState without functions all is well. 

Does anyone maybe have an idea how to approach this problem? I'm having a hard time thinking of a solution. Only a hint where to look to solve the issue would be very appreciated already!

This is my very simple reducer, almost literally copied from the example:

```
import { createReducer } from 'actionware';
import { loadUsers } from '../actions/entities';
import { createState } from 'stateware'

const initialState = createState({
  users: [],
  genderFilter: null,
  
  filteredUsers({ users, genderFilter }) {
    return users.filter(user => !genderFilter || user.gender === genderFilter);
  },
})


export default createReducer(initialState)
  .on(loadUsers, 
    (state, users) => initialState.copy({users: users }))
```
Does anyone see anything wrong here?
Thanks in advance & if I need to provide something more please do tell,

Abel

**Comment by wellguimaraes** [comment]
Hey @abeltje1 ,

Sorry for the delay. I didn't get a notification for this issue and ended up taking a long time without monitoring.

Well, seems it's a limitation with Object.assign while using React Native. I've replaced the code using that by an alternative to perform the same task and pushed on v2.2.0

Please check it out if it's still in time.

Cheers!

**Comment by abeltje1** [comment]
hey @wellguimaraes,

That's no problem, thanks a lot for looking into it anyway! I've abandoned stateware in my current project, but am very glad to be able to re-introduce it because I loved how it made my code look. Thanks again for this beautiful lib!

Cheers,

Abel
